name: Mypy, Black and Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  types-formatting-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        
    - name: Run tests
      run: poetry run pytest .

    - name: Run black
      run: poetry run black --check .
    